### ISSUE TITLE
IDEA 2024.1+ occasionally breaks run configs

### ISSUE THREAD

**Issue by rlnt** [neoforged/NeoGradle#160]
The new update for IntelliJ 2024.1 and above (currently using 2024.1.1) occasionally breaks the run configs. Even when clearing your caches and reimporting an existing project, run configs may break. Run configs that were generated on 2023 versions are always broken after updating. This is reproducible and confirmed by multiple people.

The problem is that the module is not specified so the run config is invalid.

This is the error you have when using run configs from 2023 versions after updating to 2024:
![](https://i.imgur.com/NloACoH.png)

And this is the error you have when reimporting the project and regenerating the run configs:
![](https://i.imgur.com/RkzSbTs.png)

You can fix this by setting the module manually but that only works with the second scenario.

Other people have confirmed this as well:
![](https://i.imgur.com/XW2vvRr.png)

A similar discussion started here but I think this was not continued so I am submitting this issue to keep track of it:
![](https://i.imgur.com/r8W6fQF.png)

**Comment by marchermans** [comment]
You need to either delete the .idea directory or modify the modules in the xml file.
Nothing we can do, IDEA changed the internal format, but the ids are still the same.

**Comment by rlnt** [comment]
I know I need to delete that but even then the modules won't load properly without manually specifying them. I don't think this should be closed.

**Comment by shartte** [comment]
To give some context:

We've observed that IJ suddenly starts enabling module groups, causing the IJ modules to suddenly be named differently (i.e. `appeng.ae2.main` rather than `ae2.main`).
To create the IDE run configurations we're using JetBrains [official plugin](https://github.com/JetBrains/gradle-idea-ext-plugin) and pass it a reference to the Gradle project and source set. Apparently it is unable to then figure out what the actual effective module name in IntelliJ is gonna be. 

That makes it impossible for us to do anything about this. During the project sync, there is no way to access the generated IJ module names :-|
