### ISSUE TITLE
[7.0.151] Can no longer use run configurations

### ISSUE THREAD

**Issue by bconlon1** [neoforged/NeoGradle#219]
Run configurations seem to not properly work after updating NeoGradle, e.g. the client run configuration: https://gist.github.com/bconlon1/2739124def6ecde1ef1579eedf3870d0. `clientIdeBeforeRun` seems to still exist in the list of tasks though, but the configuration can't seem to find it.

**Comment by ChampionAsh5357** [comment]
This seems to be a result of changing the import property to `idea.sync.active`. This property is only set during project reloads from build scripts compared to `idea.active` which gets set whenever an IDE task is run. Since the run configurations do not reload the project, the value is not set.

So, this issue is only for IDEA run configurations.

**Comment by marchermans** [comment]
Should be fixed in 7.0.152
